### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by irmeahegyrul** [smallo92/xnTattoos#5]
How can i fix it? 
![image](https://user-images.githubusercontent.com/60858776/87857173-85d7c880-c91c-11ea-80c0-dc1327511b46.png)

I added the sql and that a longtext but its say data too long.. How? 😂

**Comment by irmeahegyrul** [comment]
![image](https://user-images.githubusercontent.com/60858776/87857209-d94a1680-c91c-11ea-8c2c-705b0a87c0da.png)

**Comment by XvenDeR** [comment]
![image](https://user-images.githubusercontent.com/29688478/87860467-5938a680-c946-11ea-8561-668a5d943231.png)

**Comment by XvenDeR** [comment]
u r using old esx_tattooShop not xnTattoos

**Comment by irmeahegyrul** [comment]
Yeah thats my bad!
